### ISSUE TITLE
Tomatoflix no longer up

### ISSUE THREAD

**Issue by tdmalone** [jameskang410/scraping-netflix#5]
Tomatoflix, as mentioned in the README, no longer seems to be up (it's now a pregnancy food search tool - and given it says copyright 2015, congratulations on your son/daughter who would have been born by now!). Are you still using this Netflix scraper anywhere online? Does it still work?

**Comment by jameskang410** [comment]
Hey, sorry about the late reply. I got tired of paying for the domain, so just moved it over to: http://tomatoflix.jameskang.me/

However, it's not very useful because it hasn't been updated in a long, long time... the Netflix scraper doesn't work anymore. I haven't had time to snoop around the code but I'm guessing it's bc they moved to React and changed some things in the front.

**Comment by codebrainz** [comment]
FWIW, the domain linked in the description and README now refers to a seriously scummy, malicious website.
